AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB TTL DynamoDB Stack

Resources:
  TheQueensGuard:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: createdAt
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  TableName:
    Value: !Ref TheQueensGuard
